### ISSUE TITLE
Region Oceania (-region OC)

### ISSUE THREAD

**Issue by annaparker** [russianvivi/bc2rome#3]
The default region is OC which means Oceania. I think Europe should be default as most servers there. However updating bc2rome.sh let's say to region -EU before run docker command still does not change region and it is OC. Seems need to be fixed.

**Comment by UpYoursMicrosoft** [comment]
I was able to change the region by changing `-region OC` to `-region NAm` in bc2rome.sh. I think it can be set in ServerOptions.ini but I haven't tested it.

`NA` didn't work for North America. It had to be `NAm`. Europe should be `EU` according to [this thread](https://www.unknowncheats.me/forum/battlefield-bad-company-2-a/64227-bad-company-2-server.html).

I'm using Podman and podman-compose and since I was messing with the build beforehand I had to bring everything down and delete the containers and run `podman image prune -a ` before it would rebuild with the latest changes.

compose.yaml:
```yaml
services:
  bc2:
      build: ./bc2rome
      container_name: bc2
      restart: unless-stopped
      volumes:
        - /home/username/appdata/bc2:/project/R34_Full/Instance
      ports:
        - 19567:19567/udp # Main game port
        - 5900:5900/tcp   # VNC
        - 48888:48888/tcp # Admin control port
```

bc2rome.sh:
```bash
#! /bin/bash
winetricks dinput8
winetricks vcrun2005
winetricks vcrun2008
winetricks vcrun2010
export DISPLAY=:1
Xvfb :1 -screen 0 800x600x16 &
x11vnc -bg -reopen -forever
cd /project/R34_Full
wine Frost.Game.Main_Win32_Final.exe -serverInstancePath "Instance/" -mapPack2Enabled 1 -port 19567 -timeStampLogNames -region NAm -heartBeatInterval 20000
```
